---
title: "Untitled"
author: "Sean Slattery"
date: "2025-12-09"
output: html_document
---


Kalshi url: https://kalshi-public-docs.s3.amazonaws.com/reporting/trade_data_2025-02-08.json




Kalshi Market Data URL: https://kalshi-public-docs.s3.amazonaws.com/reporting/market_data_2025-12-07.json

# create a json fetch that gets all the data on the ticker = KXNCAAFPLAYOFF-25 from the start date to the end date

```{r}
library(jsonlite)
library(tidyverse)
library(dplyr)

start_Date <- as.Date("2025-09-17")
end_date   <- as.Date("2025-12-07")


fetch_daily_data <- function(single_date, tickers) {
  date_str <- format(single_date, "%Y-%m-%d")
  url <- paste0(
    "https://kalshi-public-docs.s3.amazonaws.com/reporting/market_data_",
    date_str,
    ".json"
  )
  
  tryCatch({
    daily_data <- fromJSON(url)

    # If the relevant data is nested, you may need daily_data <- daily_data$markets (or similar)
    # but assuming ticker_name is a column in daily_data:
    daily_data <- daily_data %>%
      dplyr::filter(ticker_name %in% tickers) %>%
      dplyr::mutate(date = single_date)  # optional but handy

    if (nrow(daily_data) == 0L) {
      return(NULL)
    } else {
      return(daily_data)
    }
  }, error = function(e) {
    message(paste("Data for", date_str, "not found. Skipping..."))
    return(NULL)
  })
}

dates_to_process <- seq.Date(start_Date, end_date, by = "day")  # 82 days
list_of_markets <- lapply(dates_to_process, fetch_daily_data, tickers = tickers)
market_data <- bind_rows(list_of_markets)

nrow(all_data)

head(all_data)
# ideally: 82 days * 58 tickers = 4756 rows (if every ticker appears every day)

```


```{r}
library(jsonlite)
library(tidyverse)
library(dplyr)


start_Date <- as.Date("2025-09-17")
end_date   <- as.Date("2025-12-07")


fetch_daily_data <- function(single_date) {
  date_str <- format(single_date, "%Y-%m-%d")
  url <- paste0("https://kalshi-public-docs.s3.amazonaws.com/reporting/trade_data_", date_str, ".json")
  
  
  tryCatch({
    daily_data <- fromJSON(url)
    return(daily_data)
  }, error = function(e) {
    message(paste("Data for", date_str, "not found. Skipping..."))
    return(NULL)
  })
}


dates_to_process <- seq.Date(start_Date, end_date, by = "day")

list_of_dataframes <- lapply(dates_to_process, fetch_daily_data)

all_data <- bind_rows(list_of_dataframes)
head(all_data)
# filter, group_by ticker_name, get a list of all unique values in "ticker_name"

tickers <- all_data %>%
   filter(report_ticker == "KXNCAAFPLAYOFF") %>%
   group_by(ticker_name) %>%
   distinct(ticker_name)


tickers <- as.list(tickers$ticker_name)

tickers

NCAA_trade25 <- all_data %>%
  filter(ticker_name %in% tickers)


write.csv(NCAA_trade25, "NCAA_trade25.csv")

```






